#!/usr/bin/env bash
#
#
#
e="echo"
sctle="sudo systemctl enable"
senstall="sudo pacman -S --noconfirm --needed"
# Set Time ntp on systohc
sudo pacman -Syyy
sudo timedatectl set-ntp true
sudo hwclock --systohc
# Install deps for making rustup
$senstall gcc gcc-libs cmake make ninja sddm
#
$senstall yay
#
# Installing zramd and timeshift
yay -S zram-init timeshift timeshift-autosnap
# Enabling zramd
$sctle --now zram-swap
$sctle --now zram-btrfs
# Installing hyprland and deps
#
cat "$HOME/repos/arch-base-install/pkg-files/hyprpkgs-minimal.txt" | while read -r line
do
    if [[ ${line} == '--END OF INSTALL--' ]]; then
        continue
    fi
    $e "INSTALLING: ${line}"
    yay -S --noconfirm --needed "${line}"
done
#
# Enabling sddm service
$sctle sddm
$e "minimal install complete please reboot"
