#!/usr/bin/env bash
#
#
#
e="echo"
sctle="sudo systemctl enable"
senstall="sudo pacman -Sy --noconfirm"
# Set Time ntp on systohc
sudo timedatectl set-ntp tru
sudo hwclock --systoh
# Install deps for making rustup
$senstall gcc gcc-libs cmake make ninja
# Install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# Update source in shell
chmod +x $HOME/.cargo/env
source $HOME/.cargo/env
# Install pikaur
if [[ ! -d ~/repos ]]; then
    mkdir repos
    cd repos || cd ... || return
    git clone https://aur.archlinux.org/pikaur.git
    cd pikaur || cd exit || return
    makepkg -si
    cd || cd ... || return
    rm -rf repos/pikaur
else
    cd repos || cd ... || return
    git clone https://aur.archlinux.org/pikaur.git
    cd pikaur || cd exit || return
    makepkg -si
    cd || cd ... || return
    rm -rf repos/pikaur
fi
# Installing zramd and timeshift
pikaur -S zramd timeshift timeshift-autosnap
# Enabling zramd
$sctle --now zramd
# Installing starship
cargo install starship
# Installing hyprland and deps
cat $HOME/repos/arch-base-install/pkg-files/hyprpkgs.txt | while read line
do
    if [[ ${line} == '--END OF INSTALL--' ]]; then
        # If selected installation type is FULL, skip the --END OF THE MINIMAL INSTALLATION-- line
        continue
    fi
    echo "INSTALLING: ${line}"
    pikaur -S --noconfirm --needed ${line}
done

$e "Installing Lutris Dependencies"
cat $HOME/arch-base-install/pkg-files/lutris-deps.txt | while read line
do
    if [[ ${line} == '--END OF INSTALL--' ]]; then
        continue
    fi
    $e "INSTALLING: ${line}"
    pacman -Sy --noconfirm --needed ${line}
$e "Installing Lutris Dependencies"
cat $HOME/arch-base-install/pkg-files/lutris-deps.txt | while read line
do
    if [[ ${line} == '--END OF INSTALL--' ]]; then
        continue
    fi
    $e "INSTALLING: ${line}"
    pacman -Sy --noconfirm --needed ${line}
done

done

# Enabling sddm service
$sctle sddm
# Todo add git repo for dot files
git clone https://github.com/abugger1/dots.git $HOME/repos
# cd $HOME/repos/dots/ || cd exit || return
# rsync -avxAHXP --exclude '.git*' .* ~/
