#!/usr/bin/env bash
#
#
#
e="echo"
sctle="sudo systemctl enable"
senstall="sudo pacman -S --noconfirm"
# Set Time ntp on systohc
sudo pacman -Syyy
sudo timedatectl set-ntp true
sudo hwclock --systohc
# sudo localectl  set-locale LANG=" en_US.UTF-8" LC_TIME=" en_US.UTF-8"
# Install deps for making rustup
$senstall gcc gcc-libs cmake make ninja
# Install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
Update source in shell
source $HOME/.cargo/env

$senstall yay

# Installing zramd and timeshift
yay -S zramd timeshift timeshift-autosnap
# Enabling zramd
$sctle --now zramd
# Installing starship
cargo install starship
# Installing hyprland and deps

cat $HOME/repos/arch-base-install/pkg-files/hyprpkgs.txt | while read line
do
    if [[ ${line} == '--END OF INSTALL--' ]]; then
        continue
    fi
    echo "INSTALLING: ${line}"
    yay -S --needed ${line}
done

$e "Installing Lutris Dependencies"
cat $HOME/repos/arch-base-install/pkg-files/lutris-deps.txt | while read line
do
    if [[ ${line} == '--END OF INSTALL--' ]]; then
        continue
    fi
    $e "INSTALLING: ${line}"
    yay -Sy --noconfirm --needed ${line}
done

# Enabling sddm service
$sctle sddm
# Todo add git repo for dot files
# git clone https://github.com/abugger1/dots.git $HOME/repos
# cd $HOME/repos/dots/ || cd exit || return
# rsync -avxAHXP --exclude '.git*' .* ~/
