#!/usr/bin/env bash
# Set Vars
e="echo"
senstall="sudo pacman -S --noconfirm --needed"
sudo pacman -Syu --noconfirm
# -------------------------------------
# Install flatpak
# -------------------------------------
if [ ! -d /usr/bin/flatpak ]; then
  $senstall flatpak
else
  $e "flatpak is already installed"
  exit
fi
# ------------------------------------
Install Steam
# ------------------------------------
flatpak install flathub com.valvesoftware.Steam
flatpak run com.valvesoftware.Steam
# -------------------------------------
# Install heroic
# -------------------------------------
sudo flatpak install flathub com.heroicgameslauncher.hgl
flatpak run com.heroicgameslauncher.hgl
# -------------------------------------
# Install lutrus
# -------------------------------------
flatpak install flathub net.lutris.Lutris
flatpak run net.lutris.Lutris
# -------------------------------------
Install proton-up-qt
# -------------------------------------
sudo flatpak install flathub net.davidotek.pupgui2
flatpak run net.davidotek.pupgui2
# ------------------------------------
# Install Bottles
# ------------------------------------
sudo flatpak install flathub com.usebottles.bottles
flatpak run com.usebottles.bottles


   sudo pacman -S --needed --noconfirm lutris

$e "Installing Lutris Dependencies"
cat "$HOME/repos/arch-base-install/pkg-files/lutris-deps.txt" | while read -r line
do
    if [[ ${line} == '--END OF INSTALL--' ]]; then
        continue
    fi
    $e "INSTALLING: ${line}"
    sudo pacman -S --noconfirm --needed "${line}"
done
