#!/usr/bin/env bash
#
#
source $HOME/arch-base-install/pkg-files
#
sctle="sudo systemctl enable"
senstall="sudo pacman -Sy --noconfirm"
# Set Time ntp on systohc
sudo timedatectl set-ntp tru
sudo hwclock --systoh
# Install deps for making rustup
$senstall gcc gcc-libs cmake make ninj
# Install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# Update source in shell
chmod +x $HOME/.cargo/env
source $HOME/.cargo/env
# Install paru-bin
if [[ ! -d ~/repos ]]; then
    mkdir repo
    cd repo || cd ... || return
    git clone https://github.com/paru-bin.git
    cd paru-bin || cd exit || return
    makepkg -si
    cd || cd ... || return
    git clone https://github.com/paru-bin.git
    rm -rf repos/paru-bin
  else
    cd repo || cd ... || return
    git clone https://github.com/paru-bin.git
    cd paru-bin || cd exit || return
    makepkg -si
    cd || cd ... || return
    git clone https://github.com/paru-bin.git
    rm -rf repos/paru-bin
fi
# Installing zramd and timeshift
paru -s zramd timeshift timeshift-autosnap
# Enabling zramd
$sctle --now zramd
# Installing starship
cargo install starship
# Installing hyprland and deps
paru -Sy --needed ${hyprpkgs.txt}
# Enabling sddm service
$sctle sddm
# Todo add git repo for dot files
git clone https://github.com/abugger1/hyprlanddots/tree/master
cd $HOME/repos/dots/ || cd exit || return
# rsync -avxAHXP --exclude '.git*' .* ~/
